### ISSUE TITLE
HN does not work anymore?

### ISSUE THREAD

**Issue by questor** [charlieegan3/serializer#44]
Hi! It seems HackerNews is not working since 2 days, any idea? (Also would be fine that you don't have time to debug so that I setup my own private server for this to debug it since I really like your small site)

**Comment by yoDon** [comment]
I'm also seeing this issue

**Comment by charlieegan3** [comment]
Hi both , thanks for raising the issue. I haven't had time to look into the issue yet.

I can see that serializer is being blocked now from HN after a recent update, with a 403 status.

If anyone had time to open a PR, I think that we can make the [hn scraper](https://github.com/charlieegan3/serializer/blob/main/lib/scrapers/hacker_news.rb) look like one of the [RSS scrapers](https://github.com/charlieegan3/serializer/blob/main/lib/scrapers/ars_technica.rb) instead, sourcing the data from the 'Front Page' feed at https://hnrss.github.io.

**Comment by charlieegan3** [comment]
I see that the scraper seems to be getting allowed again, I think since there are recent items this can be closed. Feel free to re-open if this comes up again or there are other issues.

**Comment by yoDon** [comment]
Any advice for folks with existing, synchronized links? 

If I go into private mode serializer shows HN links but if I view serializer normally in any of my browsers where I'm syncing my state, the HN links are still missing.

**Comment by charlieegan3** [comment]
Hmm, that's odd. What sources do you have selected? 

<img width="330" alt="Screenshot 2024-01-19 at 21 52 43" src="https://github.com/charlieegan3/serializer/assets/1774239/406faeda-f8f2-4744-a59d-599d18472e49">

**Comment by yoDon** [comment]
Doh! Must have accidentally deactivated HN while trying to confirm originally if this issue was happening. Fixed.
