### ISSUE TITLE
HN job posts have no comments

### ISSUE THREAD

**Issue by lewispeckover** [charlieegan3/serializer#9]
Job posts (eg. https://news.ycombinator.com/item?id=13696847) have no comments link.
It looks like the scraper just assumes the last link is for comments, and so the end result is that the comments link on serializer ends up being a link to hide the post.

**Comment by charlieegan3** [comment]
Hey, just tidying up this repo a little. I don’t believe HN allows comments on job listings.

See Dang’s comment here: https://news.ycombinator.com/item?id=22767319

**Comment by charlieegan3** [comment]
Oops, just read this... I’ll leave open in case I find time to fix that! 😊

**Comment by charlieegan3** [comment]
Should be fixed in 13f02564bd49919dd6f2af4ea066849d764ef7b8
